# Generated by Django 6.0.1 on 2026-02-02 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_category_description_alter_category_category_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
    ]
